services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: washika-frontend
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-washikadao.xyz}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-washikadao.xyz}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-clingyking007@gmail.com}
    expose:
      - "80"
    networks:
      - proxy-tier
    depends_on:
      - nginx-proxy

  frontend-staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: washika-frontend-staging
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_STAGING:-staging.washikadao.xyz}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_STAGING:-staging.washikadao.xyz}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-clingyking007@gmail.com}
    expose:
      - "80"
    networks:
      - proxy-tier
    depends_on:
      - nginx-proxy

  # If you add a backend that needs the shared Postgres, add it here and connect to db-tier as well:
  # backend:
  #   image: your-backend-image
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@shared-postgres:5432/${POSTGRES_DB}
  #   networks:
  #     - proxy-tier
  #     - db-tier

networks:
  proxy-tier:
    external: true
  # Uncomment if you add a backend that needs the shared db
  # db-tier:
  #   external: true 