# This docker-compose.yml defines services for your application.

services:
  app:
    build: .  # Build the image from the current directory's Dockerfile.
    ports:
      - "3000:3000"  # Map port 8080 on the host to port 8080 in the container. all backends use 8080  --for traefik use port 3000 to avoid conflicts with the proxy
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    restart: on-failure  # Restart the container if it exits with a non-zero status code.


