name: Deploy via Docker Compose

on:
  push:
    branches: [prod, staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /root/server-space/deployed-applications/wadao/WashikaDao/Washika-dao-frontend

            # Clean up old containers
            docker compose rm -f -s -v || true

            # Determine which branch triggered the workflow
            if [ "${GITHUB_REF##*/}" = "prod" ]; then
              git fetch origin prod
              git checkout prod
              git pull origin prod
              docker compose build frontend
              docker compose up -d frontend

              # Check status and logs
              if ! docker ps | grep washika-frontend; then
                echo "Frontend container is not running! Printing logs:"
                docker logs washika-frontend || true
                exit 1
              fi

            elif [ "${GITHUB_REF##*/}" = "staging" ]; then
              git fetch origin staging
              git checkout staging
              git pull origin staging
              docker compose build frontend-staging
              docker compose up -d frontend-staging

              # Check status and logs
              if ! docker ps | grep washika-frontend-staging; then
                echo "Staging container is not running! Printing logs:"
                docker logs washika-frontend-staging || true
                exit 1
              fi

            else
              echo "Not a deploy branch. Skipping."
            fi