name: Deploy via Docker Compose

on:
  push:
    branches: [prod, staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /root/server-space/deployed-applications/wadao/WashikaDao/Washika-dao-frontend
            # Determine which branch triggered the workflow
            if [ "${GITHUB_REF##*/}" = "prod" ]; then
              git fetch origin prod
              git checkout prod
              git pull origin prod
              docker compose build frontend
              docker compose up -d frontend
            elif [ "${GITHUB_REF##*/}" = "staging" ]; then
              git fetch origin staging
              git checkout staging
              git pull origin staging
              docker compose build frontend-staging
              docker compose up -d frontend-staging
            else
              echo "Not a deploy branch. Skipping."
            fi