name: Deploy via Docker Compose

on:
  push:
    branches: [prod, staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/server-space/deployed-applications/wadao/washika-dao-frontend
            git pull origin prod
            docker compose build frontend
            docker compose up -d 
            git pull origin staging
            docker compose build frontend-staging
            docker compose up -d frontend-staging