name: Deploy Frontend

on:
  push:
    branches:
      - prod
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          BRANCH=${GITHUB_REF##*/}
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '
            cd /root/server-space/deployed-applications/wadao/WashikaDao &&
            git fetch origin $BRANCH &&
            git checkout $BRANCH &&
            git pull origin $BRANCH &&
            cd Washika-dao-frontend &&
            docker compose -f docker-compose.yml up -d --build
          ' 